[package]
name = "rust_gpio"
version = "0.1.0"
authors = ["ysngndz <ysngndz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = ""
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
